sudo: required

os:
  - osx
  - linux

language: node_js

addons:
  chrome: beta

before_install:
  - npm i -g npm@6

node_js:
  - "8"
  - "11.10.1"

# https://docs.travis-ci.com/user/gui-and-headless-browsers/#Starting-a-Web-Server
# https://github.com/travis-ci/travis-ci/issues/7313#issuecomment-279914149
before_script:
  - npm run setup
  - export DISPLAY=:99.0
  - if [ "${TRAVIS_OS_NAME}" = "osx"   ]; then (sudo Xvfb :99 -ac -screen 0 1024x768x8; echo ok)& fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then (sh -e /etc/init.d/xvfb start) fi
  - sleep 3                             # give xvfb some time to start

script:
  - npm run lint:nofix
  - npm run test
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then (npm run bench) fi
